apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-machine
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: docker-machine
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - 'create'
  - 'get'
  - 'delete'
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  - virtualmachines
  verbs:
  - get
  - delete
  - create
  - update
  - patch
  - list
  - watch
- apiGroups:
  - subresources.kubevirt.io
  resources:
  - virtualmachines/start
  - virtualmachines/stop
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: docker-machine
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: docker-machine
subjects:
- kind: ServiceAccount
  name: docker-machine
  namespace: default
